version: "3.9"

services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./api:/code
    environment:
      DB_HOST: db
      DB_PORT: 27017
      DB_NAME: project

  db:
    image: mongo:latest
    volumes:
      - database-storage:/run/db
    ports:
      - 27017:27017

volumes:
    database-storage:
