services:
  server:
    build: ./server
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db
    working_dir: /code
    volumes:
      - ./server:/code
    environment:
      DB_HOST: db
    env_file:
      - .env
  db:
    image: mongo:latest
    volumes:
      - database-storage:/run/db
    ports:
      - 27017:27017
    logging:
      driver: "none"
volumes:
    database-storage: