services:
  server:
    build: ./server
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db
    working_dir: /code
    volumes:
      - ./server:/code
volumes:
    database-storage: